#!/bin/sh
if test $# -eq 0
then
  echo "Usage Error: ./scriptCompile [filenameToCompile] [entrada] "
  exit 1
fi
#Aqui compilamos el programa
if gcc -c -Wall -Wshadow $1
then
  gcc -o ejecutable *.o
fi


#ejecutable
if test $# -gt 1
then
  ./ejecutable <$2
elif test $# -gt 2
then
  echo "Usage Error: ./scriptCompile [filenameToCompile] [Entrada Comandos(si no se introduce nada la entrada es el terminal)]"
  exit 1
else
  ./ejecutable
fi
